name: Code Checks

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Spoof code checks
        run: 'true'

  gating-tests:
    name: Run Gating Tests
    runs-on: ubuntu-latest
    steps:
      - name: Spoof gating tests
        run: 'true'
